language: node_js
node_js:
  - node
services:
  - docker
sudo: false
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - docker-compose up -d
install:
  - npm ci
after_script:
  - npm run coverage
