language: node_js
node_js:
  - node
services:
  - docker
sudo: false
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - cp .env.testing .env
  - docker-compose up --build -d
install:
  - npm ci
after_script:
  - docker-compose down
  - npm run coverage
