language: node_js
node_js:
  - node
services:
  - docker
sudo: false
cache:
  directories:
    - '$HOME/.npm'
install:
  - npm ci
before_script:
  - cp .env.testing .env
  - docker-compose up --build -d
  - npm run key:generate
after_script:
  - npm run coverage
  - docker-compose down
