version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - mockup-financial-db:/data/db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
volumes:
  mockup-financial-db:
    driver: "local"
